authentication:
  configtype: yaml
  userstorage:
    type: sql
    sqlconnection:
     driver: mysqli
     host: 127.0.0.1
     port: 3306
     user: test
     password: test
     dbname: authn
     charset: utf8
    table: userinfo
    mappingpath: "/var/www/jardin/auth-n/src/doctrine.mapping/"
    maxrequestregister: 3
    maxrequestresetpassword: 3
  auth:
  - name: mysql
    # type: sql, ldap, oidc, oauth2, cas, saml
    type: sql
    # zero possition implies default which is 'writable'
    order: 0
    config:
     sqlconnection:
      driver: mysqli
      host: "127.0.0.1"
      port: 3306
      user: test
      password: test
      dbname: authn
      charset: utf8
     table: users
     usercol: "uid"
     passwordcol: password
     asciikey: def0000022bab6743ba2fd70af012ae041e520139bca6d367ea0deda488e7b90ddbab25a0f941a8cb12e0661b2f955d14c46995e54392829552a83807a48313d7ba2efc2
  - name: openldap
    type: ldap
    order: 2
    config:
     host: "127.0.0.1"
     port: 389
     binduser: "cn=admin,dc=example,dc=org"
     bindpassword: P@ssw0rd
     basedn: "ou=people,dc=example,dc=org"
