authentication:
  configtype: yaml
  sqlconnection:
    driver: mysqli
    host: 127.0.0.1
    port: 3306
    user: test
    password: test
    dbname: authn
    charset: utf8
  ldapconnection:
    host: 127.0.0.1
    port: 389
    user: user
    password: password
    basedn: ou=auth,dc=company,dc=com
    userattribute: uid
  userstorage:
    type: sql
    table: userinfo
    maxrequestregister: 3
    maxrequestresetpassword: 3
  auth:
    type: sql
    table: users
    usercol: uid
    passwordcol: password
    asciikey: def0000022bab6743ba2fd70af012ae041e520139bca6d367ea0deda488e7b90ddbab25a0f941a8cb12e0661b2f955d14c46995e54392829552a83807a48313d7ba2efc2